import uuid
from datetime import date, datetime
from decimal import Decimal
from sqlalchemy import Boolean, Date, DateTime, ForeignKey, Integer, Numeric, String, Text, text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database.base import Base
class Customer(Base):
 __tablename__='customers'; id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('companies.id'),index=True); first_name:Mapped[str]=mapped_column(String(80)); last_name:Mapped[str]=mapped_column(String(80)); phone:Mapped[str]=mapped_column(String(40),index=True); email:Mapped[str|None]=mapped_column(String(255)); address:Mapped[str|None]=mapped_column(Text); notes:Mapped[str|None]=mapped_column(Text); is_active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=text('CURRENT_TIMESTAMP')); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=text('CURRENT_TIMESTAMP'),onupdate=text('CURRENT_TIMESTAMP'))
class Sale(Base):
 __tablename__='sales'; id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('companies.id'),index=True); customer_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('customers.id')); user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id')); sale_number:Mapped[str]=mapped_column(String(40),unique=True,index=True); subtotal:Mapped[Decimal]=mapped_column(Numeric(14,2)); discount:Mapped[Decimal]=mapped_column(Numeric(14,2),default=0); total:Mapped[Decimal]=mapped_column(Numeric(14,2)); amount_paid:Mapped[Decimal]=mapped_column(Numeric(14,2),default=0); payment_status:Mapped[str]=mapped_column(String(30)); payment_method:Mapped[str]=mapped_column(String(30)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=text('CURRENT_TIMESTAMP')); items:Mapped[list['SaleItem']]=relationship(back_populates='sale')
class SaleItem(Base):
 __tablename__='sale_items'; id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); sale_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('sales.id')); product_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('products.id')); quantity:Mapped[int]=mapped_column(Integer); unit_price:Mapped[Decimal]=mapped_column(Numeric(14,2)); discount:Mapped[Decimal]=mapped_column(Numeric(14,2),default=0); subtotal:Mapped[Decimal]=mapped_column(Numeric(14,2)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=text('CURRENT_TIMESTAMP')); sale:Mapped[Sale]=relationship(back_populates='items')
class Credit(Base):
 __tablename__='credits'; id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('companies.id'),index=True); customer_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('customers.id')); sale_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('sales.id'),unique=True); original_amount:Mapped[Decimal]=mapped_column(Numeric(14,2)); amount_paid:Mapped[Decimal]=mapped_column(Numeric(14,2),default=0); remaining_amount:Mapped[Decimal]=mapped_column(Numeric(14,2)); due_date:Mapped[date|None]=mapped_column(Date); status:Mapped[str]=mapped_column(String(30)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=text('CURRENT_TIMESTAMP')); payments:Mapped[list['Payment']]=relationship(back_populates='credit')
class Payment(Base):
 __tablename__='payments'; id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('companies.id'),index=True); credit_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('credits.id')); customer_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('customers.id')); user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id')); amount:Mapped[Decimal]=mapped_column(Numeric(14,2)); payment_method:Mapped[str]=mapped_column(String(30)); reference:Mapped[str|None]=mapped_column(String(100)); notes:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=text('CURRENT_TIMESTAMP')); credit:Mapped[Credit]=relationship(back_populates='payments')
